[
	{
	"Nombre": "Kia Forte",
	"Anio":"2016",
	"categoria": "livianos",
	"precio": "7,900",
	"transmision": "Estandar",
	},
	{
	"Nombre": "Toyota Corolla",
	"Anio":"2010",
	"categoria": "Livianos",
	"precio": "6,000",
	"transmision": "Estandar",
	},
	{
	"Nombre": "Nissan Pathfinder",
	"Anio":"2013",
	"categoria": "Livianos",
	"precio": "9,750",
	"transmision": "Automatica",
	},
	{
	"Nombre": "Nissan Pathfinder",
	"Anio":"2013",
	"categoria": "Livianos",
	"precio": "9,750",
	"transmision": "Automatica",
	},
	{
	"Nombre": "TOYOTA LC PRADO",
	"Anio":"2012",
	"categoria": "Livianos",
	"precio": "13,000",
	"transmision": "Automatica",
	},
	{
	"Nombre": "KIA OPTIMA",
	"Anio":"2013",
	"categoria": "Livianos",
	"precio": "7000",
	"transmision": "Estandar",
	},
	{
	"Nombre": "Furgon Freightliner",
	"Anio":"2003",
	"categoria": "Pesados",
	"precio": "15,000",
	"transmision": "Estandar",
	},
	{
	"Nombre": "Hyundai Porter",
	"Anio":"2012",
	"categoria": "Pesados",
	"precio": "13,200",
	"transmision": "Estandar",
	},
	{
	"Nombre": "ISUZU QKR",
	"Anio":"2018",
	"categoria": "Pesados",
	"precio": "16,000",
	"transmision": "Estandar",
	},
	{
	"Nombre": "KIA PICANTO",
	"Anio":"2014",
	"categoria": "livianos",
	"precio": "4000",
	"transmision": "Estandar",
	},
	{
	"Nombre": "Toyota Hilux",
	"Anio":"2020",
	"categoria": "Pesados",
	"precio": "29,000",
	"transmision": "Automatica",
	},
	{
	"Nombre": "Mitsubishi Outlander",
	"Anio":"2018",
	"categoria": "livianos",
	"precio": "10,000",
	"transmision": "Automatica",
	},
	{
	"Nombre": "Mazda 3",
	"Anio":"2010",
	"categoria": "livianos",
	"precio": "5,000",
	"transmision": "Automatica",
	},
	
	
